name: Bump Version

# Documentation with macOS virtual environment:
# https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer

jobs:
  Bump_version:
    name: Bump Version
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Create bump version branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'bump-version'

      - name: Bump version
        # fastlane is by default installed on macOS runners
        run: |
          bundle install
          bundle exec fastlane bump_version

      - name: Debug commands
        run: |
          git show-ref
          git name-rev HEAD

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Bump version
          title: Bump version
          assignees: lexorus
          base: master

      - name: Print created PR number
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"

      - name: Delete branch
        if: failure()
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: bump-version
