name: Bump Version

# Documentation with macOS virtual environment:
# https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.3.app/Contents/Developer

jobs:
  Bump_version:
    name: Bump Version
    runs-on: macos-latest

    env:
      BRANCH: bump-version
      BASE_BRANCH: master

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create bump version branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.BRANCH }}

      - name: Checkout to bump version branch
        uses: actions/checkout@v1
        with:
          ref: ${{ env.BRANCH }}

      - name: Bump version
        # fastlane is by default installed on macOS runners
        run: |
          bundle install
          bundle exec fastlane bump_version

      - name: Create PR
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Bump version
          title: Bump version
          assignees: lexorus
          base: ${{ env.BASE_BRANCH }}
          branch: ${{ env.BRANCH }}

      - name: Delete branch
        if: failure()
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ env.BRANCH }}
